#!/usr/bin/env bash
# SPDX-License-Identifier: RPL-1.5
# Copyright (C) 2026 Nick Booth, N1CCK. See LICENSE.
#
# Every source file carries the License Notice (LICENSE, EXHIBIT A) in its
# first lines. Each tracked path is classified below, and a path no class
# claims fails, so a new kind of file is a decision rather than a silent skip.
#
#   scripts/license-notices.sh check   exit 0 = every source file carries it, 1 = one lacks it or is unclassified
#   scripts/license-notices.sh apply   add it where missing (nothing is written while a path is unclassified)
#   exit 2 = bad usage
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

MODE="${1:-}"
[[ "$MODE" == check || "$MODE" == apply ]] || { echo "usage: $0 <check|apply>" >&2; exit 2; }

SPDX="SPDX-License-Identifier: RPL-1.5"
COPYRIGHT="Copyright (C) 2026 Nick Booth, N1CCK. See LICENSE."
# A shebang or a doctype has to stay on line 1, so the notice may sit below
# one; deeper than this it is no longer where a reader looks for it.
HEAD_LINES=5

# Third-party files keep their own licence; NOTICE is the list of them. An
# entry's further files sit on indented continuation lines under `Files:`.
mapfile -t VENDORED < <(awk '
    /^[[:space:]]+Files?:[[:space:]]+[^[:space:]]+/ { infiles = 1; print $2; next }
    infiles && /^[[:space:]]+[^[:space:]:]+[[:space:]]*$/ { print $1; next }
    { infiles = 0 }' NOTICE 2>/dev/null)

is_vendored() {
    local v; for v in "${VENDORED[@]}"; do [[ "$v" == "$1" ]] && return 0; done
    return 1
}

# The comment style a path takes, `exempt`, or nothing when unclassified.
style_of() {
    is_vendored "$1" && { echo exempt; return; }
    case "$1" in
        # An applied migration's bytes are its checksum in every deployed ledger.
        backend/migrations/*.sql) echo exempt ;;
        # Generated by tools/email/build.mjs from the .mjml sources, which carry the notice.
        backend/crates/*/templates/*.html) echo exempt ;;
        # mkdocs partials are Jinja; a template comment is never rendered into a page.
        overrides/*.html) echo jinja ;;
        *.rs | *.ts | *.tsx | *.js | *.mjs | *.cjs) echo slash ;;
        *.css) echo block ;;
        *.html | *.mjml) echo html ;;
        *.sh | *.yml | *.yaml | *.toml | *.tpl | *.template | *.example | Containerfile | */Containerfile | scripts/git-hooks/*) echo hash ;;
        # No comment syntax, generated, documentation, binary, or tool metadata.
        *.json | *.lock | *.md | *.png | *.svg | *.ico | *.txt) echo exempt ;;
        .gitignore | */.gitignore | .gitattributes | .containerignore | .dockerignore) echo exempt ;;
        .github/CODEOWNERS | NOTICE | LICENSE | scripts/check-structure.allow) echo exempt ;;
        *) echo "" ;;
    esac
}

has_notice() {
    local head; head="$(head -n "$HEAD_LINES" "$1")"
    grep -qF -- "$SPDX" <<< "$head" && grep -qE -- 'Copyright \(C\) [0-9]{4}' <<< "$head"
}

notice_block() { # style
    local open close
    case "$1" in
        slash) open='// ' close='' ;;
        hash) open='# ' close='' ;;
        block) open='/* ' close=' */' ;;
        html) open='<!-- ' close=' -->' ;;
        jinja) open='{# ' close=' #}' ;;
    esac
    printf '%s%s%s\n%s%s%s\n' "$open" "$SPDX" "$close" "$open" "$COPYRIGHT" "$close"
}

# Rewritten through `cat >` so the file keeps its mode, executable bits included.
write_notice() { # path style
    local first tmp
    first="$(head -n 1 "$1")"
    tmp="$(mktemp)"
    if [[ "$first" == '#!/'* || "${first,,}" == '<!doctype'* ]]; then
        { head -n 1 "$1"; notice_block "$2"; tail -n +2 "$1"; } > "$tmp"
    else
        { notice_block "$2"; cat "$1"; } > "$tmp"
    fi
    cat "$tmp" > "$1"
    rm -f "$tmp"
}

missing=()
unclassified=()
declare -A STYLE=()
while IFS= read -r path; do
    [[ -f "$path" ]] || continue
    style="$(style_of "$path")"
    if [[ -z "$style" ]]; then unclassified+=("$path"); continue; fi
    [[ "$style" == exempt ]] && continue
    has_notice "$path" || { missing+=("$path"); STYLE[$path]="$style"; }
done < <(git ls-files)

for path in "${unclassified[@]}"; do echo "$path: unclassified: add it to a class in $0"; done
if ((${#unclassified[@]} > 0)); then exit 1; fi

if [[ "$MODE" == apply ]]; then
    for path in "${missing[@]}"; do write_notice "$path" "${STYLE[$path]}"; done
    echo "license-notices: added to ${#missing[@]} file(s)"
    exit 0
fi

for path in "${missing[@]}"; do echo "$path: no license notice in its first $HEAD_LINES lines"; done
if ((${#missing[@]} > 0)); then
    echo "license-notices: ${#missing[@]} file(s) without the notice; run $0 apply"
    exit 1
fi
echo "license-notices: clean"
